In [1]:
import xgboost

In [2]:
!pip install xgboost

In [3]:
import pandas as pd # Pandas is a library written for the Python programming language for data manipulation and analysis.
import numpy as  np  # numpy is library written for the python programming language for mathematical functions .

In [4]:
dataset=pd.read_csv("insurance_pre.csv") #import csv file 

In [5]:
dataset

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [6]:
dataset=pd.get_dummies(dataset,drop_first=True)


In [7]:
dataset

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [8]:
dataset=dataset.astype(int)

In [9]:
dataset

age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [10]:
dependent=dataset[['charges']]
dependent

charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [11]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [12]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent
                    

age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [14]:
X_train.values

array([[18, 28,  0,  0,  0],
       [39, 32,  0,  0,  0],
       [52, 46,  5,  0,  0],
       ...,
       [40, 25,  0,  1,  0],
       [19, 35,  0,  1,  0],
       [33, 18,  1,  0,  0]])

In [15]:
import xgboost as xg
from xgboost import XGBRegressor
from sklearn.svm import SVR
rgr= SVR(C=1.0, epsilon=0.2)

In [16]:
rgr.fit(X_train,Y_train)


C:\Users\premchandar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(epsilon=0.2)

In [17]:
y_pred=rgr.predict(X_test)

In [18]:
y_pred

array([9593.1275351 , 9563.70097059, 9571.97346327, 9633.03100373,
       9579.57149761, 9484.76273441, 9426.63725687, 9588.63024209,
       9508.78460699, 9470.71499105, 9485.40515213, 9580.02905407,
       9539.00292171, 9479.23805899, 9451.93905347, 9581.0014463 ,
       9626.53968705, 9449.23908448, 9508.3497491 , 9430.88184121,
       9584.57421832, 9614.14816091, 9593.06562054, 9562.97276441,
       9436.99240894, 9479.30329365, 9459.44041857, 9522.10174637,
       9469.19852836, 9551.84107709, 9520.17360197, 9624.19552654,
       9636.74486033, 9609.08605942, 9443.5793229 , 9464.54192387,
       9560.14223511, 9460.30397542, 9521.82661242, 9432.15508793,
       9495.68659177, 9460.0020989 , 9513.58772931, 9622.81588029,
       9431.23774232, 9433.87476065, 9580.51347443, 9531.70404729,
       9465.33100612, 9613.55418959, 9440.51712119, 9428.51049905,
       9569.48283654, 9588.75151241, 9620.22798707, 9459.24821716,
       9451.33864358, 9579.98569575, 9537.61671198, 9626.60801

In [19]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,y_pred)

In [20]:
r_score

-0.08844250999130221

In [21]:
import pickle
filename="finalized_model_XGboost.sav"

In [22]:
pickle.dump(rgr, open(filename,"wb"))

In [23]:
loaded_model=pickle.load(open("finalized_model_XGboost.sav","rb"))
result=loaded_model.predict([[55413,14567,365448,0,1]]) 
result 

C:\Users\premchandar\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(


array([9538.15998982])